enum Icon {
    static let logo = "logo"
    static let caretRight = "caretRight"
    static let home = "home"
    static let more = "more"
    static let new = "new"
    static let profileImage = "profileImage"
    static let search = "search"
    
    // System
    static let systemPlayFill = "play.fill"
    static let systemPlus = "plus"
    static let systemTVFill = "4k.tv.fill"
    static let systemCheckmark = "checkmark"
    static let systemSettings = "gearshape.fill"
    static let systemUser = "person.fill"
    static let systemInfo = "info.circle"
    static let systemEdit = "pencil"
    static let systemChevron = "chevron.right"
    static let systemBell = "bell"
    static let systemPlayCircle = "play.circle"
    static let systemFilm = "film"
    static let systemArrowDownCircle = "arrow.down.circle"
    static let systemThumbsUp = "hand.thumbsup"
    static let systemThumbsUpFill = "hand.thumbsup.fill"
    static let systemShare = "square.and.arrow.up"
    static let systemDownSquare = "arrow.down.square"
}
